#ifndef SFX_LAYOUT_H
#define SFX_LAYOUT_H

// Auto-generated by tools/generate_sfx.py from music/sfx/*.vgm's
// command streams -- do not edit by hand, regenerate instead:
//   python3 tools/generate_sfx.py
//
// Byte offsets into the SFX_DATA XRAM region (constants.h) of each
// clip's command stream. src/sfx.h's SFX_*_ADDR macros add these
// to SFX_DATA to get the absolute XRAM address
// sfx_play_player()/sfx_play_enemy() take.
#define SFX_PLYRFIRE_OFFSET 0
#define SFX_PLYRFIRE_LEN    115
#define SFX_ENMYFIRE_OFFSET 115
#define SFX_ENMYFIRE_LEN    115
#define SFX_ENMYDIE_OFFSET 230
#define SFX_ENMYDIE_LEN    133
#define SFX_PLYRHIT_OFFSET 363
#define SFX_PLYRHIT_LEN    97
#define SFX_PLYRDIE_OFFSET 460
#define SFX_PLYRDIE_LEN    223
#define SFX_PICKUP_OFFSET 683
#define SFX_PICKUP_LEN    133
#define SFX_TALLY_OFFSET 816
#define SFX_TALLY_LEN    133
#define SFX_LVLCLEAR_OFFSET 949
#define SFX_LVLCLEAR_LEN    94
#define SFX_LOWENRGY_OFFSET 1043
#define SFX_LOWENRGY_LEN    61
#define SFX_XTRALIFE_OFFSET 1104
#define SFX_XTRALIFE_LEN    583
#define SFX_VICTORY_OFFSET 1687
#define SFX_VICTORY_LEN    517

#define SFX_DATA_SIZE 2204

#endif
